
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Feb 18 11:43:35 IST 2020
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MINUS = 4;
  public static final int DIVIDE = 6;
  public static final int UMINUS = 13;
  public static final int NUMBER = 16;
  public static final int EOFILE = 9;
  public static final int MOD = 7;
  public static final int SEMI = 2;
  public static final int EOF = 0;
  public static final int PLUS = 3;
  public static final int NL = 8;
  public static final int TYPE = 10;
  public static final int ID = 11;
  public static final int COMMA = 12;
  public static final int error = 1;
  public static final int RPAREN = 15;
  public static final int TIMES = 5;
  public static final int LPAREN = 14;
}

